{% set name = "caproto" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nsls-ii/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 61f28af8846ad10645837f6de4438ae6c82c36cecabbd64a353ec3b6a723a8e3

build:
  noarch: python
  entry_points:
    - caproto-get = caproto.commandline.get:main
    - caproto-put = caproto.commandline.put:main
    - caproto-monitor = caproto.commandline.monitor:main
    - caproto-repeater = caproto.commandline.repeater:main
    - caproto-defaultdict-server = caproto.ioc_examples.defaultdict_server:main
    - caproto-spoof-beamline = caproto.ioc_examples.spoof_beamline:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - asks
    - curio
    - dpkt
    - netifaces
    - numpy
    - trio

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/nsls-ii/caproto
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'a bring-your-own-IO implementation of the EPICS Channel Access protocol in pure Python'

extra:
  recipe-maintainers:
    - CJ-Wright
