{% set name = "caproto" %}
{% set version = "0.8.1" %}
{% set sha256 = "fee8264fe4b0550196ea7aafc7e68b10d5ef51c7747a6286bde0c945f85b3ab4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - caproto-get = caproto.commandline.get:main
    - caproto-put = caproto.commandline.put:main
    - caproto-monitor = caproto.commandline.monitor:main
    - caproto-repeater = caproto.commandline.repeater:main
    - caproto-shark = caproto.commandline.shark:main
    - caproto-defaultdict-server = caproto.ioc_examples.pathological.defaultdict_server:main
    - caproto-spoof-beamline = caproto.ioc_examples.pathological.spoof_beamline:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - asks
    - curio
    - dpkt
    - netifaces
    - numpy
    - trio

test:
  imports:
    - caproto
  commands:
    - caproto-get -h
    - caproto-get --help
    - caproto-put --help
    - caproto-monitor --help
    - caproto-repeater --help
    - caproto-shark --help
    - which caproto-defaultdict-server
    - which caproto-spoof-beamline
    - echo -e "\n" | caproto-spoof-beamline & (pid=$! ; sleep 5 ; kill -SIGINT $pid)

about:
  home: http://github.com/caproto/caproto
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a bring-your-own-IO implementation of the EPICS Channel Access protocol in pure Python
